export const products = [
    {id: 1,
     name: "Green Apple",
     price: 14.99,
     oldPrice: 20.99,
     image: "/images/popularproduct.png",
     rating: 4,
     sale: 50
 },
 {id: 2,
    name: "Fresh Indian malta",
    price: 20.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
{id: 3,
    name: "Chinese cabbage",
    price: 12.00,
    oldPrice: 24.00,
    image: "/images/popularproduct.png",
    rating: 4,
   featured: true,
   brand: 'Farmery',
  brandImage: '/images/brandimg.png',
  description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra...',
  category: 'Vegetables',
  tags: ['Vegetables', 'Healthy', 'Chinese', 'Cabbage', 'Green Cabbage'],
  weight: '03',
  color: 'green',
  type:'organic',
  stockStatus: 'Available'
},
{id: 4,
    name: "Green Lettuce",
    price: 9.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 5,
    name: "Eggplant",
    price: 34.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 6,
    name: "Big Potatoes",
    price: 20.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 7,
    name: "Corn",
    price: 20.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 8,
    name: "Fresh Cauliflower",
    price: 12.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 9,
    name: "Green Capsicum",
    price: 9.00,
    oldPrice: 20.99,
    image: "/images/popularproduct.png",
    rating: 4,
    sale: 50
   },
   {id: 10,
    name: "Green Chilli",
    price: 34.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 11,
    name: "Big potatoes",
    price: 12.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 12,
    name: "Corn",
    price: 12.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 13,
    name: "Red Tomatoes",
    price: 9.00,
    oldPrice: 20.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 14,
    name: "Surjapur Mango",
    price: 34.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 15,
    name: "Badami Mango",
    price: 34.00,
    image: "/images/popularproduct.png",
    rating: 4
   },
   {id: 16,
    name: "Mango",
    price: 34.00,
    image: "/images/popularproduct.png",
    rating: 4
   }
   
];